language: node_js
node_js:
- '8'
- '10'
after_success: npm run coverage
deploy:
  provider: npm
  email: scaldwell77
  api_key:
    secure: VCH7dOfQNczfhYJGpLq4SZ4yQqHthPozEW+c20BzUL92bhDQ01Lf6KrKncLTJJbOLiXU7O6JwAO9fAT9zJTs9aBKEW1NLdkE5+MscbWfLk4fwZrsaRab91zrGeJuP6DzURCHWEyapXZBV/Qw1l1vvkWPsvYMv7FC2+EtpZYbIPOuowmosMwMnmz3Yx9K5cCdS8er3IkokszuyAC7KCvwPDY5j7A9tV6zLe9D4h2yw83P+rUSBceMQiw21yDKN2OJmDLL0VQxMIBmaW1saaYIwvHdPhWnqC9viUPD1Kvke7YqxBACytUxc83LRnOYHVGnmFVDlGeXw5CfJv6zcokRFSMsn4uCLqS6etvXu9yAp5FXtjO+BfmRB6prZc5ZbBF5/b/l+sx9gdFkCAwmmogwlF4oDkJeu1vpbXX3Xomu2ILbnPLaa2pcHUKiandxFT4REab7WKc83Fd4bt00OReDTpLgPK0dXC1hL0fjWnKHyXmx5cPiz175rRXBF8N2jY9YRKf16Kkjd7zgfxY5l1kNqKlaSlbpPfKH0N5MmYbfVMwHlOnJnHzo6kUaPaoVogASvOiqA5mkslmSM2ThIp2EZpbQPyiJPMN0FB4k4A5cSv2Uccq5NxIN+Tdq6tQaYQ+VRiL1MTEidpvLeliS6ydsyHV6NAaA+IU3Q7k+OrM7N3w=
  on:
    tags: true
    repo: stevecaldwell77/hebo-js
    node: '8'
