language: node_js
node_js:
- '8'
- '10'
script: npm run test-coverage
after_success: npm run coverage
deploy:
  provider: npm
  email: scaldwell@gmail.com
  api_key:
    secure: DCVgCQG4EZ0MkYVP+i7J9QWeiaK58i9XWKojtw7hIQRjVzBaO64O2Ry50wbtkn/ptcfU1SJBa/GjF9ZV+ntVvpy9CRCn450ljtTavCVGx+MEjamVrN0ntf4Pn3fDME3wCgeq8BEkem9uBhUcPjJSt3hhUH2/24+zn3x0TVfbhS5EK/6zqqvri30faCd4VGCfUtMfYhJZQkKJl1NynDGnwUPFOfrrfW1Rw2vlaT6v3+iPVKpIZwxWbQoO5uSw/axTJyVKOaRClaYBPUSHbGrQ7JCHCoDhcGtYhpDBWqmIKsk8yHO+RY39UXR6xN1nqrFfBZOl6t5PtoUqnVSkKgPiocjSY09Zhht44mRla8yn0D9cE8IfE3SzCERDEP3keqLTNXKhvf6pYxIapgiM6cL4mej7TWEGE9T9Sk+8+2GvZBxy7VTLy6ZS6wq/tcKN3at9O8/eRrkRrkACALzx1c04NwuJOAzKkIVeeMOn9XwT6QqcItzZjW648jT09k16v8CBL1lCUYN2RoDupjrOiQGcPaXuunggQS8fcvYpVpcHEHx+AtsmdDbPFTKQrRX1KoTFJlBByC31fOsHwHt9i9ocNsegFbRRRkJF2h1Wjq3ingO4YKMvtGKG77IWY+k55nZkZHm2epRweNGgGluhFL0CXbl3Uba25AJfBbbzf9yGEtA=
  on:
    tags: true
    repo: stevecaldwell77/hebo-js
    node: '8'
